const FIGHT_TIMEOUT_MS = 5 * 60 * 1000;
const DEFAULT_PLAYER_COOLDOWN_MS = 4000;
const TOWER_COOLDOWN_MS = 3000;
const BARUT_MULTIPLIER = 1.10;
const ZIRH_MULTIPLIER = 0.90;
const EXPLOSIVE_MULTIPLIER = 1.6;
const BOT_BASE_DAMAGE = 155;
const PVP_CANNON_DAMAGE = 185;
const PVP_NPC_BASE_DAMAGE = 150;
const BOT_AMMO_DAMAGE = { 1: 30, 2: 75, 3: 130 };
const DEFAULT_NPC_FALLBACK = { hp: 10000, damage: 200, gold: 300, xp: 50, pearl: 0 };
const WEEKLY_BOSS_HP = 100000000;
const WEEKLY_BOSS_DMG = 500;
const TIAMAT_HP = 12000000;
const TIAMAT_DMG = 5000;
const CLEANUP_INTERVAL_MS = 60 * 1000;
const PVP_AMMO_CHECK_LIMIT = 1000;
const TOWER_MIN_LEVEL = 5;
const TOWER_MAX_LEVEL = 100;
const TOWER_BASE_HP = 20000;
const TOWER_HP_PER_LEVEL = 5000;
const TOWER_BASE_DAMAGE = 100;
const TOWER_DAMAGE_PER_LEVEL = 80;
const TOWER_BASE_PEARL = 150;
const TOWER_PEARL_PER_LEVEL = 50;
const BOT_BASE_HP = 25000;
const BOT_HP_PER_LEVEL = 6500;
const BOT_BASE_CANNONS = 10;
const BOT_CANNONS_PER_LEVEL = 2;
const BOT_SHIP_LVL_DIVISOR = 2;

const BOT_CANNON_TYPES = [
  { id: 1, name: 'Light', damage: 120, reloadMs: 1500 },
  { id: 2, name: 'Medium', damage: 185, reloadMs: 2500 },
  { id: 3, name: 'Heavy', damage: 280, reloadMs: 4000 }
];

const BOT_AMMO_TYPES = [
  { id: 1, damageBonus: 30 },
  { id: 2, damageBonus: 75 },
  { id: 3, damageBonus: 130, givesElp: true }
];

module.exports = {
  FIGHT_TIMEOUT_MS,
  DEFAULT_PLAYER_COOLDOWN_MS,
  TOWER_COOLDOWN_MS,
  BARUT_MULTIPLIER,
  ZIRH_MULTIPLIER,
  EXPLOSIVE_MULTIPLIER,
  BOT_BASE_DAMAGE,
  PVP_CANNON_DAMAGE,
  PVP_NPC_BASE_DAMAGE,
  BOT_AMMO_DAMAGE,
  DEFAULT_NPC_FALLBACK,
  WEEKLY_BOSS_HP,
  WEEKLY_BOSS_DMG,
  TIAMAT_HP,
  TIAMAT_DMG,
  CLEANUP_INTERVAL_MS,
  PVP_AMMO_CHECK_LIMIT,
  TOWER_MIN_LEVEL,
  TOWER_MAX_LEVEL,
  TOWER_BASE_HP,
  TOWER_HP_PER_LEVEL,
  TOWER_BASE_DAMAGE,
  TOWER_DAMAGE_PER_LEVEL,
  TOWER_BASE_PEARL,
  TOWER_PEARL_PER_LEVEL,
  BOT_BASE_HP,
  BOT_HP_PER_LEVEL,
  BOT_BASE_CANNONS,
  BOT_CANNONS_PER_LEVEL,
  BOT_SHIP_LVL_DIVISOR,
  BOT_CANNON_TYPES,
  BOT_AMMO_TYPES
};
