-- Up
ALTER TABLE players ADD COLUMN IF NOT EXISTS dmg_pve BIGINT DEFAULT 0;
ALTER TABLE players ADD COLUMN IF NOT EXISTS dmg_pvp BIGINT DEFAULT 0;
ALTER TABLE players ADD COLUMN IF NOT EXISTS kill_npc INT DEFAULT 0;
ALTER TABLE players ADD COLUMN IF NOT EXISTS kill_pvp INT DEFAULT 0;
ALTER TABLE players ADD COLUMN IF NOT EXISTS dmg_amiral BIGINT DEFAULT 0;
ALTER TABLE players ADD COLUMN IF NOT EXISTS playtime INT DEFAULT 0;

-- Down
ALTER TABLE players DROP COLUMN IF EXISTS playtime;
ALTER TABLE players DROP COLUMN IF EXISTS dmg_amiral;
ALTER TABLE players DROP COLUMN IF EXISTS kill_pvp;
ALTER TABLE players DROP COLUMN IF EXISTS kill_npc;
ALTER TABLE players DROP COLUMN IF EXISTS dmg_pvp;
ALTER TABLE players DROP COLUMN IF EXISTS dmg_pve;
