-- Up
ALTER TABLE players ADD COLUMN IF NOT EXISTS pvp_points INT DEFAULT 0;
ALTER TABLE players ADD COLUMN IF NOT EXISTS pvp_target_id INT DEFAULT NULL;
ALTER TABLE players ADD COLUMN IF NOT EXISTS pvp_changes_left INT DEFAULT 10;
ALTER TABLE players ADD COLUMN IF NOT EXISTS last_pvp_reset DATE DEFAULT CURRENT_DATE;
ALTER TABLE active_fights ADD COLUMN IF NOT EXISTS is_pvp BOOLEAN DEFAULT false;

-- Down
ALTER TABLE active_fights DROP COLUMN IF EXISTS is_pvp;
ALTER TABLE players DROP COLUMN IF EXISTS last_pvp_reset;
ALTER TABLE players DROP COLUMN IF EXISTS pvp_changes_left;
ALTER TABLE players DROP COLUMN IF EXISTS pvp_target_id;
ALTER TABLE players DROP COLUMN IF EXISTS pvp_points;
