-- Up
ALTER TABLE players ADD COLUMN IF NOT EXISTS is_admin BOOLEAN DEFAULT false;
ALTER TABLE players ADD COLUMN IF NOT EXISTS is_banned BOOLEAN DEFAULT false;
ALTER TABLE players ADD COLUMN IF NOT EXISTS ban_reason TEXT DEFAULT NULL;
ALTER TABLE players ADD COLUMN IF NOT EXISTS banned_at TIMESTAMP DEFAULT NULL;
ALTER TABLE players ADD COLUMN IF NOT EXISTS ban_expires_at TIMESTAMP DEFAULT NULL;
ALTER TABLE players ADD COLUMN IF NOT EXISTS device_id VARCHAR(255) DEFAULT NULL;
ALTER TABLE players ADD COLUMN IF NOT EXISTS banned_devices TEXT[] DEFAULT '{}';

-- Down
ALTER TABLE players DROP COLUMN IF EXISTS banned_devices;
ALTER TABLE players DROP COLUMN IF EXISTS device_id;
ALTER TABLE players DROP COLUMN IF EXISTS ban_expires_at;
ALTER TABLE players DROP COLUMN IF EXISTS banned_at;
ALTER TABLE players DROP COLUMN IF EXISTS ban_reason;
ALTER TABLE players DROP COLUMN IF EXISTS is_banned;
ALTER TABLE players DROP COLUMN IF EXISTS is_admin;
