-- Up
ALTER TABLE players ADD COLUMN IF NOT EXISTS is_bot BOOLEAN DEFAULT FALSE;
ALTER TABLE players ADD COLUMN IF NOT EXISTS bot_map_level INT DEFAULT NULL;

-- Down
ALTER TABLE players DROP COLUMN IF EXISTS is_bot;
ALTER TABLE players DROP COLUMN IF EXISTS bot_map_level;
