/* ══════════════════════════════════════════════
   SeaPirates — Global i18n Dil Sistemi (lang.js)
   English data embedded (always available)
   Other languages: js/lang/XX.js (lazy loaded)
══════════════════════════════════════════════ */

const I18N_DATA = {};

// Prevent content flash by hiding the page until translations are applied.
// Adds `i18n-loading` class to <html> and a small style to hide body while loading.
(function () {
  try {
    if (document && document.documentElement) {
      document.documentElement.classList.add('i18n-loading');
      var _style = document.createElement('style');
      _style.innerHTML = '.i18n-loading body{visibility:hidden !important;opacity:0;}';
      (document.head || document.getElementsByTagName('head')[0]).appendChild(_style);
    }
  } catch (e) { /* ignore */ }
})();

I18N_DATA['en'] = {
    btn_back: '◀ BACK',
    btn_menu: 'MENU',
    btn_save: 'SAVE',
    btn_login: 'SET SAIL',
    btn_register: 'BECOME A PIRATE',
    btn_logout: '⚓ LOG OUT',
    btn_play: 'PLAY',
    btn_harbor: 'HOME',
    btn_equipment: 'EQUIPMENT',
    btn_return: 'RETURN',
    btn_attack: 'ATTACK',
    btn_search: 'SEARCH NPC',
    btn_repair: 'REPAIR',
    btn_stop_repair: 'STOP',
    login_title: 'Login',
    register_title: 'Register',
    username_label: 'Username',
    username_placeholder: 'Enter username...',
    password_label: 'Password',
    password_placeholder: 'Enter password...',
    email_label: 'Email',
    email_placeholder: 'Your email address...',
    remember_me: 'Remember Me',
    no_account: "Don't have an account?",
    has_account: 'Already a member?',
    register_link: 'Register Now',
    login_link: 'Login',
    login_error_fields: 'Please fill in all fields.',
    register_success: 'Registration successful! You can now log in.',
    welcome_captain: 'Welcome, Captain!',
    vip_status_off: 'Not VIP',
    vip_status_on: '👑 VIP Active',
    top_pirates: 'Top 100 Pirates',
    leaderboard_title: 'Rankings',
    rank_score: 'Rank Score',
    battle_points: 'Battle Points',
    rank_label: 'Rank',
    starter_pack: 'STARTER PACK',
    pack_name_baslangic: '🌟 Crew Pack',
    pack_name_korsan: '⚓ Captain\'s Pack',
    pack_name_kaptan: '👑 Sea Lord Pack',
    pack_baslangic_1: '20,000 🪙 Gold + 1,000 💎 Pearl',
    pack_baslangic_2: '1,000 Gunpowder + 1,000 Armor',
    pack_baslangic_3: '5,000 Hollow Shot + 2,000 Explosive Shot',
    pack_korsan_1: '50,000 🪙 Gold + 3,000 💎 Pearl',
    pack_korsan_2: '3,000 Gunpowder + 3,000 Armor',
    pack_korsan_3: '15,000 Hollow Shot + 7,000 Explosive Shot',
    pack_korsan_4: '2× 55-Pounder Cannon + 5× Wooden Beam',
    pack_kaptan_1: '100,000 🪙 Gold + 6,000 💎 Pearl',
    pack_kaptan_2: '8,000 Gunpowder + 8,000 Armor',
    pack_kaptan_3: '35,000 Hollow Shot + 18,000 Explosive Shot',
    pack_kaptan_4: '3× 60-Pounder Cannon + 10× Elite Beam',
    pack_kaptan_5: 'Seahawk Design',
    vip_pack: 'VIP PACKS',
    buy_now: 'BUY NOW',
    searching: '🔍 SEARCHING...',
    monster_not_found: 'No monsters detected!',
    level_required: 'Level too low! Required Level: ',
    weekly_boss_title: 'LEVIATHAN',
    btn_weekly_boss: 'WEEKLY BOSS',
    boss_subtitle: '⚓ Weekly Admiral Hunt',
    admiral_appeared: '{name} appeared on Map {map}-{sub}!',
    boss_section_title: '🏴‍☠️ Highest Damage Rankings',
    glitter_back: 'BACK TO MAP',
    glitter_title: 'GLITTER',
    glitter_reward: '✨ Reward:',
    glitter_empty: 'Collect glitter from the sea to earn rewards!',
    glitter_collect_fail: 'Could not collect glitter.',
    ammo_name_grapeshot: 'Grapeshot',
    ammo_name_hollow: 'Hollow',
    ammo_name_explosive: 'Explosive',
    daily_tower_title: 'DAILY TOWER',
    victory: 'VICTORY',
    defeat: 'SUNK',
    pvp_victory_msg: "You sank {name}'s ship.",
    pvp_defeat_msg: 'You were defeated by {name}!',
    pvp_header: 'PVP RESULT',
    reward_header: 'REWARDS',
    reward_warning_line1: 'This map is too easy for you now.',
    reward_warning_line2: 'Let new players grow stronger.',
    btn_attack_anyway: 'Attack Anyway',
    level_up: '🎉 LEVELED UP!',
    no_cannons_title: 'NO CANNONS EQUIPPED!',
    no_cannons_desc: 'You must equip at least 1 cannon to enter battle.',
    combat_timer: 'BATTLE TIME',
    target_hp: 'Target HP',
    shop_title: 'SHOP',
    auction_title: 'AUCTION',
    item_cannons: 'CANNONS',
    item_ammo: 'AMMO',
    item_beams: 'BEAMS',
    item_consumables: 'CONSUMABLES',
    highest_bid: 'Highest Bid',
    place_bid: 'PLACE BID',
    no_bids_yet: 'No bids yet',
    time_left: 'Time Left',
    auction_ended: 'ROUND ENDED',
    auc_barut_name: 'Gunpowder x100',
    auc_barut_desc: '+10% attack damage. Consumed on each shot.',
    auc_zirh_name: 'Armor x100',
    auc_zirh_desc: '-10% incoming damage. Consumed on each shot.',
    auc_gul3_name: 'Explosive Cannonball x2000',
    auc_gul3_desc: 'Damage: +130. Elite Points: 1.0/cannon.',
    auc_top2_name: '55 Pounder',
    auc_top2_desc: '185 dmg/cannon. Reload: 3 sec.',
    auc_top3_name: '60 Pounder',
    auc_top3_desc: '260 dmg/cannon. Reload: 2 sec.',
    auc_elit_kiris_name: 'Elite Beam',
    auc_elit_kiris_desc: '+1,200 HP bonus, Repair +20. Low break chance.',
    auc_gemi1_name: 'Elite Ship I',
    auc_gemi1_desc: '25,000 HP, 30 cannon / 10 beam slots.',
    auc_kristal_queen_name: 'Crystal Queen Design',
    auc_kristal_queen_desc: 'Cosmetic only. Gives your ship a crystal coating appearance.',
    auc_kristal_queen_design_name: 'Crystal Queen Design',
    auc_kristal_queen_design_desc: 'Cosmetic only. Gives your ship a crystal coating appearance.',
    insufficient_gold: 'Not enough gold!',
    bid_success: 'Bid placed successfully!',
    buy_success: 'Purchase successful!',
    item_ships: 'SHIPS',
    item_designs: 'DESIGNS',
    settings_title: 'SETTINGS',
    section_language: 'Language Settings',
    section_general: 'General Settings',
    section_account: 'Account Settings',
    section_session: 'Session Management',
    lang_label: 'Game Language',
    lang_desc: 'Select your language',
    sound_title: 'Sound Effects',
    sound_desc: 'Cannon fire, explosions and ambient sounds.',
    graphics_title: 'Graphics Mode',
    graphics_desc: 'Battle background animations (birds, fish etc.).',
    particles_title: 'Particle Effects',
    particles_desc: 'Water particles and wave animations on the map.',
    username_note: 'You can only change your username once per week.',
    username_success: 'Username changed successfully!',
    profile_id: 'ID',
    profile_level: 'Level',
    profile_reg_date: 'Registration Date',
    profile_reg_date_unknown: 'Unknown',
    profile_vip: 'VIP',
    profile_vip_inactive: 'Not Active',
    btn_change_username: 'CHANGE USERNAME',
    username_length_error: 'Username must be between 3-30 characters.',
    username_error: 'Failed to change username!',
    logout_msg: 'Logged out successfully.',
    toast_sound_updated: 'Sound settings updated.',
    toast_graphics_updated: 'Graphics settings updated.',
    toast_particles_updated: 'Particle settings updated.',
    toast_language_updated: 'Language changed.',
    forgot_password: 'Forgot Password',
    repassword_placeholder: 'Re-enter password...',
    terms_link: 'Terms of Service',
    accept_terms: 'I agree.',
    btn_events: '🎉 EVENTS',
    npc_damage_label: 'Damage:',
    npc_loot_label: 'Loot:',
    menu_shop: 'Shop',
    menu_equipment: 'Equipment',
    menu_ships: 'Ships',
    menu_auction: 'Auction',
    menu_my_hall: 'My Hall of Fame',
    menu_hall_of_fame: 'Hall of Fame',
    menu_daily_reward: 'Daily Login Reward',
    menu_level_bonus: 'Level Bonus',
    menu_clan: 'Clan',
    menu_settings: 'Settings',
    menu_admin: 'Admin',
    admin_tab_players: 'Players',
    admin_tab_logs: 'Logs',
    admin_col_username: 'Username',
    admin_col_status: 'Status',
    admin_badge_admin: 'ADMIN',
    admin_badge_banned: 'BANNED',
    admin_badge_vip: 'VIP',
    admin_badge_ok: 'ACTIVE',
    admin_search: 'Search',
    admin_filter: 'Filter',
    admin_log_all: 'All',
    admin_no_results: 'No results found',
    reg_error_username: '3–20 characters, letters/numbers/_ only.',
    reg_error_email: 'Enter a valid email address.',
    reg_error_password: 'Password must be at least 6 characters.',
    reg_error_pass2: 'Passwords do not match.',
    reg_error_terms: 'You must accept the terms.',
    login_error_generic: 'Login failed',
    login_welcome: '⚓ Welcome {name}!',
    register_error_generic: 'Registration failed',
    register_welcome: '⚔ Captain {name}, welcome to the seas!',
    forgot_error_nouser: 'Enter your username first.',
    forgot_success: '📧 Password reset link sent.',
    strength_weak: 'Weak',
    strength_medium: 'Medium',
    strength_good: 'Good',
    strength_strong: 'Strong',
    bottom_privacy: 'Privacy Policy',
    bottom_terms: 'Terms of Service',
    modal_close: 'OK',
    exit_confirm_title: 'EXIT APP',
    exit_confirm_msg: 'Are you sure you want to exit?',
    exit_confirm_yes: 'YES',
    exit_confirm_no: 'NO',
    fight_back_title: 'FIGHT IN PROGRESS',
    fight_back_msg: 'If you leave now, your progress will be lost! Are you sure?',
    back_double_tap: 'Press back again to exit',
    modal_terms_title: '⚓ TERMS OF SERVICE',
    modal_privacy_title: '🛡️ PRIVACY POLICY',
    quest_accepted: 'Quest accepted!',
    quest_accept_failed: 'Quest could not be accepted!',
    quest_cancelled: 'Quest cancelled!',
    quest_cancel_failed: 'Cancel failed!',
    quest_delivered: 'Quest delivered!',
    quest_deliver_failed: 'Quest could not be delivered!',
    quest_bonus_delivered: 'Bonus quest delivered!',
    quest_submit_failed: 'Submit failed!',
    quest_no_active: 'You have no active quests.<br>Get a new quest from the "Available Quests" tab!',
    quest_no_available: 'No new quests are available right now.',
    quest_all_done: 'You have completed all quests!',
    quest_tab_active: 'ACTIVE QUEST',
    quest_tab_available: 'AVAILABLE QUESTS',
    quest_btn_accept: 'ACCEPT QUEST',
    quest_max_active: 'MAX ACTIVE QUESTS',
    quest_btn_deliver: 'DELIVER',
    quest_btn_cancel: 'CANCEL',
    quest_btn_claim: 'CLAIM REWARD',
    quest_locked_req: 'LEVEL {val} REQUIRED',
    quest_completed: '✓ COMPLETED',
    quest_time_left: 'TIME LEFT',
    quest_times_up: "TIME'S UP",
    quest_bonus_time: '30MIN',
    quest_level_badge: 'Lv. {val}',
    q_title_1: 'Novice Crew',
    q_title_2: 'Cannon Fire',
    q_title_3: 'Glitter Hunter',
    q_title_4: 'Wild Waters',
    q_title_5: 'Damage Storm',
    q_title_6: 'Deep Dive',
    q_title_7: 'Pirate Hunter',
    q_title_8: 'Line of Fire',
    q_title_9: 'Glitter Thief',
    q_title_10: 'Over Tortuga',
    q_title_11: 'Dreadful Damage',
    q_title_12: 'Sea\'s Secret',
    q_title_13: 'Red Corsair Threat',
    q_title_14: 'Firepower',
    q_title_15: 'Scarlet Treasure',
    q_title_16: 'Fear Morgan',
    q_title_17: 'Fierce Waves',
    q_title_18: 'Glitter Storm',
    q_title_19: 'Chasing the Admiral',
    q_title_20: 'Siege',
    q_title_21: 'Big Hit',
    q_title_22: 'Ghost Ship Hunt',
    q_title_23: 'Dutch Curse',
    q_title_24: 'Sea Treasure',
    q_title_25: 'Ghost Fleet',
    q_title_26: 'Legendary Wreck',
    q_title_27: 'Dark Storm',
    q_title_28: 'Flyingdutchman Conqueror',
    q_title_29: 'Doomsday',
    q_title_30: 'Endless Ocean',
    q_title_101: 'Time Raid I',
    q_title_102: 'Before the Storm II',
    q_title_103: 'Pirate Storm III',
    q_title_104: 'Hell Wave IV',
    q_title_105: 'Scarlet Typhoon V',
    q_title_106: 'Deep Dark VI',
    q_title_107: 'Admiral\'s Wrath VII',
    q_title_108: 'Four Horsemen VIII',
    q_title_109: 'Ghost Storm IX',
    q_title_110: 'Doomsday Clock X',
    q_desc_1: 'First step into piracy: sink Blackpearl ships and collect glitter from the sea.',
    q_desc_2: 'Show your marksmanship by dealing 5,000 total damage to Blackpearl ships.',
    q_desc_3: 'Collect 10 glitter from the sea and sink 3 more Blackpearl ships.',
    q_desc_4: 'Sink Wild 13 ships and collect glitter. No one is safe in these waters!',
    q_desc_5: 'Deal 15,000 damage to the Wild 13 gang and prove you rule the seas.',
    q_desc_6: 'Collect 15 glitter and deal 5,000 more damage. Your pirate treasure grows!',
    q_desc_7: 'Hunt down Tortuga Gang and Wild 13. Pit them against each other!',
    q_desc_8: 'Deal 30,000 damage to Tortuga Gang. Teach them fear first!',
    q_desc_9: 'Collect 20 glitter and sink 3 Tortuga ships. You are unstoppable!',
    q_desc_10: 'Sink 8 Tortuga Gang ships and collect 10 glitter. Clean the pirate island!',
    q_desc_11: 'Deal 75,000 total damage. Let enemies remember your name in fear!',
    q_desc_12: 'Collect 25 glitter and deal 30,000 more damage to the Tortuga gang!',
    q_desc_13: 'Sink Red Korsar ships and take their glitter. The red wave will be stopped!',
    q_desc_14: 'Deal 80,000 damage to Red Korsar and 70,000 to other enemies. Show your firepower!',
    q_desc_15: 'Deal 100,000 damage to the Red Korsar fleet and capture 15 glitter!',
    q_desc_16: 'Sink 6 Morgansbuccaneers ships. Send a message to Morgan!',
    q_desc_17: 'Deal 250,000 damage to enemies and collect 15 glitter. The seas are yours!',
    q_desc_18: 'Collect 35 glitter and deal 100,000 damage to Morgan\'s men!',
    q_desc_19: 'Deal 100,000 damage to Admiral Jack and clear 4 Morgan pirates around him!',
    q_desc_20: 'Deal 200,000 damage to Morgan pirates and collect 15 glitter. They won\'t help their admiral!',
    q_desc_21: 'Deal 400,000 total damage and sink 3 Morgan ships. Pre-battle warm-up!',
    q_desc_22: 'Sink 4 Flyingdutchman ships and 4 Morgan pirates. Strike fear into ghosts!',
    q_desc_23: 'Deal 300,000 damage to Flyingdutchman ships and collect 15 glitter. Break the curse!',
    q_desc_24: 'Collect 45 glitter and sink 3 ghost ships. Time to get rich!',
    q_desc_25: 'Sink 3 Flyingdutchman ships and collect 20 glitter. The ghosts will end!',
    q_desc_26: 'Deal 800,000 total damage to enemies. Steady steps on the path to legend!',
    q_desc_27: 'Deal 500,000 damage to Flyingdutchman ships and collect 30 glitter. Stop the dark storm!',
    q_desc_28: 'Sink 5 Flyingdutchman ships and collect 40 glitter. Harbinger of the final battle!',
    q_desc_29: 'Deal 3,000,000 total damage and sink 3 more Flyingdutchman ships. Doomsday is near!',
    q_desc_30: 'Collect 80 glitter and deal 2,000,000 damage to the Flyingdutchman fleet. The legend completes!',
    q_desc_101: 'Captain! You have 30 minutes. Destroy the Blackpearl fleet!',
    q_desc_102: 'Destroy the Wild 13 gang within 30 minutes!',
    q_desc_103: 'Destroy Tortuga and Wild 13 gangs within 30 minutes!',
    q_desc_104: 'Finish the Tortuga gang within 30 minutes!',
    q_desc_105: 'Destroy the Red Korsar fleet within 30 minutes!',
    q_desc_106: 'Strike fear into Morgan within 30 minutes!',
    q_desc_107: 'Deal 200,000 damage to Admiral Jack and clear his pirates within 30 minutes!',
    q_desc_108: 'Stop the ghost fleet within 30 minutes!',
    q_desc_109: 'Destroy the Flyingdutchman fleet within 30 minutes!',
    q_desc_110: 'Land the final blow on Flyingdutchman within 30 minutes!',
    obj_kill_Blackpearl: 'Sink Blackpearl',
    'obj_kill_Wild 13': 'Sink Wild 13',
    'obj_kill_Tortuga Gang': 'Sink Tortuga Gang',
    'obj_kill_Red Korsar': 'Sink Red Korsar',
    obj_kill_Morgansbuccaneers: 'Sink Morgansbuccaneers',
    obj_kill_Flyingdutchman: 'Sink Flyingdutchman',
    obj_damage: 'Deal damage',
    obj_damage_Blackpearl: 'Deal damage to Blackpearl',
    'obj_damage_Wild 13': 'Deal damage to Wild 13',
    'obj_damage_Tortuga Gang': 'Deal damage to Tortuga Gang',
    'obj_damage_Red Korsar': 'Deal damage to Red Korsar',
    obj_damage_Morgansbuccaneers: 'Deal damage to Morgansbuccaneers',
    obj_damage_Flyingdutchman: 'Deal damage to Flyingdutchman',
    'obj_damage_Admiral Jack': 'Deal damage to Admiral Jack',
    obj_glitter: 'Collect glitter',
    lbl_sink: 'Sink',
    lbl_deal_damage: 'Deal Damage',
    lbl_collect_glitter: 'Collect Glitter',
    lbl_objectives: 'Objectives',
    any: 'Any',
    bid_placeholder: 'Bid amount',
    bid_failed: 'Bid failed!',
    currency_gold: 'Gold',
    currency_pearl: 'Pearl',
    payment_coming_soon: '🔒 {type} "{plan}" package selected. Payment system coming soon!',
    captain: 'Captain',
    black_knight: 'Black Knight',
    search_failed: 'No monsters detected in the water!',
    ranking_loading: '⏳ Loading rankings...',
    ranking_error: 'Failed to load rankings.',
    daily_boss_attack: '⚔️ Can attack <b>1 time</b> daily.<br>🔄 Reset: <b>{countdown}</b>',
    boss_already_attacked: '❌ You already attacked today!',
    lbl_hp: 'HP',
    lbl_damage: 'Damage',
    lbl_loot_none: 'None',
    lbl_coordinate: 'Coordinate',
    text_attack: 'ATTACK',
    attackable: 'ATTACKABLE',
    already_attacked: 'ATTACKED',
    repair_failed: '❌ Repair failed!',
    repair_connection_error: '❌ Could not connect to server, repair failed!',
    map_change_failed: 'Map change failed!',
    boss_weekly_reward: '{ammo} Explosive',
    success: 'Success',
    error: 'Error',
    server_error: 'Server error occurred.',
    connection_failed: 'Could not connect to server!',
    offline_title: 'CONNECTION LOST',
    offline_msg: 'Your internet connection has been lost for 30 seconds. You have been logged out for security.',
    offline_toast: 'Connection lost! Logging out in {seconds}sec...',
    unauthorized: 'Session expired, please log in again.',
    session_expired_title: 'Session Ended',
    session_expired_msg: 'Another device has logged into this account.<br>You need to log in again to continue.',
    session_expired_btn: 'LOG IN',
    invalid_amount: 'Enter a valid amount.',
    err_player_not_found: 'Player not found.',
    err_server: 'Server error.',
    err_quest_invalid_id: 'Invalid quest ID.',
    err_quest_level_mismatch: 'This quest is not for your current level.',
    err_quest_already_active: 'You already have an active quest. VIPs can take up to 2 quests!',
    err_quest_already_completed: 'You have already completed this quest.',
    err_quest_no_active_deliver: 'No active quest to deliver.',
    err_quest_not_found: 'Quest not found.',
    err_quest_objectives_pending: 'Quest objectives not yet completed!',
    err_quest_no_active_cancel: 'No active quest to cancel.',
    err_quest_no_bonus: 'No active bonus quest.',
    err_quest_bonus_expired: 'Bonus quest has expired!',
    err_quest_bonus_not_found: 'Bonus quest not found.',
    err_quest_bonus_objectives_pending: 'Bonus quest objectives not yet completed!',
    err_glitter_too_fast: 'Collecting too fast! Slow down and move your mouse.',
    err_glitter_hourly_limit: 'Hourly collection limit reached! Please wait.',
    btn_enable_notif: '🔔 Enable Notifications',
    notif_title: '🔔 Push Notifications',
    notif_desc: 'Get notified when admiral spawns.',
    notif_active: 'On',
    notif_on_desc: 'Notifications active.',
    notif_browser_blocked: 'Notifications blocked by browser. Reset from browser settings.',
    notif_error: 'Failed to enable notifications.',
    notif_unsupported: 'This browser does not support notifications.',
    page_equipment: 'EQUIPMENT',
    page_ships: 'SHIPS',
    page_my_hall: 'MY HALL',
    page_hall_of_fame: 'HALL OF FAME',
    page_daily_reward: 'DAILY LOGIN',
    page_level_bonus: 'LEVEL BONUS',
    page_events: 'EVENTS',
    events_no_past: 'No past events',
    events_captain_orders: "CAPTAIN'S ORDERS",
    events_royal_order: 'ROYAL ORDER',
    events_season_order: 'SEASON ORDER',
    events_time_remaining: 'TIME REMAINING',
    events_no_active_order: 'NO ACTIVE ORDER',
    events_next_order_in: 'NEXT ORDER IN',
    events_weekly_route: 'WEEKLY ROUTE',
    events_rotation_order: 'ROTATION ORDER',
    events_past_orders: 'PAST ORDERS',
    event_npc_reward_name: '2x NPC Reward',
    event_npc_reward_desc: 'Gold, pearl, and XP earned from NPCs are doubled!',
    event_elp_reward_name: '2x ELP Reward',
    event_elp_reward_desc: 'Earned Elite Points (ELP) are doubled!',
    event_damage_name: '2x Damage',
    event_damage_desc: 'Explosive Shot damage is doubled!',
    event_none_name: 'No Active Event',
    event_none_desc: 'There is no active event at the moment.',
    event_eff_npc_gold: 'NPC Gold Reward',
    event_eff_npc_pearl: 'NPC Pearl Reward',
    event_eff_npc_xp: 'NPC XP Reward',
    event_eff_elp_gain: 'Elite Points (ELP) gain',
    event_eff_explosive_dmg: 'Explosive Shot damage',
    event_badge_active: 'ACTIVE',
    event_badge_this_week: 'THIS WEEK',
    event_badge_next_week: 'NEXT WEEK',
    page_quest: 'QUESTS',
    page_pvp: 'PVP',
    pvp_unranked: 'Unranked',
    pvp_max: 'MAX',
    pvp_remaining: '(Remaining: {val})',
    pvp_unknown_opponent: 'Unknown Opponent',
    pvp_refresh: 'Refresh Opponents',
    page_glitter: 'GLITTER',
    page_map: 'MAP',
    page_fight: 'FIGHT',
    fight_timer_label: 'BATTLE TIME',
    fight_dmg_list: 'DMG LIST',
    fight_no_cannons_title: 'NO CANNONS EQUIPPED!',
    fight_no_cannons_desc: 'You must equip at least <b>1 cannon</b> to enter battle.<br><br>Equip cannons from the <b>Equipment</b> screen.',
    fight_btn_go_equipment: 'GO TO EQUIPMENT',
    fight_btn_go_back: 'Go Back',
    equip_storage: 'In Storage',
    equip_equipped: 'Ship',
    equip_stats_title: 'Ship Stats',
    equip_stat_hp: 'Total HP',
    equip_stat_dmg: 'Cannon Damage',
    equip_stat_reload: 'Reload Speed',
    equip_stat_repair: 'Repair Bonus',
    equip_no_storage: 'No items in storage',
    equip_empty_ship: 'Ship is empty',
    equip_pcs: 'pcs',
    equip_slot: 'slot',
    equip_equip_all: 'Equip All',
    equip_unequip_all: 'Unequip All',
    equip_tab_cannons: 'CANNONS',
    equip_tab_masts: 'MASTS',
    ships_ep_label: '💎 Elite Points (ELP)',
    ships_ep_short: 'ELP',
    design_crystal_queen: 'Crystal Queen',
    design_seahawk: 'Seahawk',
    ships_elite_next: 'Next: {name} — {amount} ELP needed',
    ships_next: 'Next',
    ships_all_unlocked: 'All ships unlocked!',
    ships_required: 'required',
    ships_tab_elite: 'ELITE SHIPS',
    ships_tab_designs: 'DESIGNS',
    ships_badge_selected: 'SELECTED',
    ships_badge_use: 'USE',
    ships_no_designs: 'You don\'t have any designs yet.<br/>Buy them from the shop!',
    ships_locked: '🔒 LOCKED',
    ships_cosmetic: 'Cosmetic only',
    ships_level: 'Level',
    ships_default: 'Default',
    ships_hp_short: 'HP',
    ships_cannon_slots: 'Cannon Slots',
    ships_mast_slots: 'Mast Slots',
    ships_already_using: 'is already in use',
    ships_insufficient_ep: 'Insufficient Elite Points!',
    ships_activated: 'activated ✅',
    ships_visual: 'Visual',
    ships_default_view: 'Default View',
    daily_month_label: 'MONTH',
    daily_title: 'DAILY LOGIN',
    daily_streak: 'Streak',
    daily_time_left: 'Time Left',
    daily_vip_short: 'VIP',
    daily_vip_not_active: 'NOT ACTIVE',
    daily_vip_active: 'ACTIVE',
    daily_progress: 'Progress',
    daily_normal_reward: 'NORMAL REWARD',
    daily_vip_reward: 'VIP REWARD',
    daily_claim: 'CLAIM',
    daily_day: 'day',
    daily_ready: 'READY',
    daily_claimed_success: 'Reward claimed successfully! 🎉',
    err_daily_already_claimed: 'You have already claimed today\'s reward!',
    err_daily_vip_not_claimable: 'Cannot claim VIP reward! You are not VIP or already claimed today.',
    err_username_change_limit: 'You can only change your username once per week. Remaining: {days} day(s)',
    err_account_banned: 'Your account has been banned.',
    ban_notification_title: 'Your Account is Banned!',
    ban_reason_label: 'Reason:',
    ban_expires_label: 'Expires:',
    ban_permanent_label: 'Permanent Ban',
    ban_date_label: 'Ban Date:',
    err_daily_claim_failed: 'Could not claim reward!',
    vip_title: '⚓ VIP MEMBERSHIP',
    vip_desc: 'Get VIP to unlock premium daily rewards,<br>HP regen bonus & more!',
    vip_7day: '7 Day VIP',
    vip_30day: '1 Month VIP',
    vip_90day: '3 Month VIP',
    vip_coming_soon: 'Payment integration coming soon',
    btn_close: 'CLOSE',
    vip_sub: 'Become a privileged pirate, buy now!',
    vip_7day_dur: '7 days of VIP privileges',
    vip_30day_dur: '30 days of VIP privileges (most popular)',
    vip_90day_dur: '90 days of VIP privileges (best value)',
    vip_perk_repair: '×2 Repair Speed — Repair your ship 2x faster in battle',
    vip_perk_daily: 'VIP Daily Rewards — 30-day premium reward calendar',
    vip_perk_level: 'VIP Level Rewards — Extra rewards on every level up',
    vip_perk_quest: '2nd Quest Slot — Take 2 quests at the same time',
    vip_perk_respawn: '+10% Respawn HP — Respawn with 10% of your max HP',
    vip_perk_shop_discount: '10% Shop Discount — 10% off on all shop items',
    level_unlocked: 'Unlocked',
    level_vip_status: 'VIP Status',
    level_lvl: 'level',
    reward_hollow: 'Hollow Shot',
    reward_explosive: 'Explosive Shot',
    reward_gunpowder: 'Gunpowder',
    reward_armor: 'Armor',
    reward_wood: 'Wooden Beam',
    reward_elite_wood: 'Elite Beam',
    page_tower: 'DAILY TOWER',
    tower_loading: 'Loading tower data...',
    tower_todays_target: "TODAY'S TARGET",
    tower_name: 'Tower (Lvl {val})',
    tower_max: '⭐ TOWER MAXIMUM ⭐',
    tower_max_hp: 'Max HP',
    tower_damage: 'Tower Damage',
    tower_reward: 'Reward:',
    tower_attack: 'START ATTACK',
    tower_req_level: 'You must be at least <b>Level 5 (Lvl 5)</b> to participate in Tower Battles!<br>Your current level: Lvl {val}',
    tower_daily_used: 'You have used your daily tower attack.<br>Try the next tower (<b>Lvl {val}</b>) tomorrow!',
    tower_status_info: 'Your tower level is set to <b>Lvl {val}</b>.<br>You can only attack once per day!',
    tower_status_max: '🏆 You completed the tower!<br>Keep attacking daily to earn pearls!',
    hall_today_rank: 'Today\'s Rank',
    hall_you: 'You',
    hall_calculated_as: 'Your rank is calculated as follows:',
    hall_desc_dmg: 'Damage / 200,000',
    hall_desc_ep: 'Elite / 5,000',
    hall_desc_xp: 'Experience / 1,500',
    hall_desc_lvl: 'Level × 100',
    hall_desc_days: 'Day × 5',
    hall_total_score: 'Total score:',
    hall_next_rank: 'For the next rank',
    hall_next_rank_desc: 'You need {val} rank points',
    hall_one_below: 'One rank below',
    hall_one_below_desc: 'You currently have {val} rank points',
    hall_note: 'Note:',
    hall_note_text: 'Ranks are calculated in real-time. The points and ranking shown here are live data. Reaching the displayed score does not guarantee the rank! Because other players are also earning points simultaneously.',
    hall_you_need: 'You need',
    hall_more_points: 'more rank points to reach the next rank.',
    hall_congrats: 'Congratulations!',
    hall_top_rank: '👑 You are at the top!',
    hall_keep_lead: 'You are currently the highest rank on the server! Keep your lead!',
    hall_the_gap: 'The gap to avoid dropping a rank is',
    hall_rank_points: 'rank points.',
    hall_lowest_rank: 'You are at the lowest rank, earn points to keep your place!',
    hall_calculating: '⚓ Calculating rank...',
    hall_fetch_error: '⚠️ Could not fetch rank data from server!',
    hall_connection_error: '⚠️ Server connection error!',
    hof_title: 'HALL OF FAME',
    hof_my_rank: 'My Rank:',
    hof_rank_header: 'Rank',
    hof_players_header: 'Players',
    hof_score_header: 'Score',
    hof_cat_xp: 'Experience Points',
    hof_cat_ep: 'Elite Points',
    hof_cat_dmg_pve: 'Damage Score PvE',
    hof_cat_dmg_pvp: 'Damage Score PvP',
    hof_cat_kill_npc: 'NPCs Sunk',
    hof_cat_kill_pvp: 'Players Sunk',
    hof_cat_dmg_amiral: 'Admiral Damage',
    hof_cat_playtime: 'Playtime',
    hof_cat_pvp_points: 'Battle Points',
    shop_name_30_pounder: '30 Pounder',
    shop_name_55_pounder: '55 Pounder',
    shop_name_60_pounder: '60 Pounder',
    shop_name_grapeshot: 'Splinter (x100)',
    shop_name_hollow_shot: 'Hollow (x100)',
    shop_name_explosive_shot: 'Explosive (x100)',
    shop_name_wooden_beam: 'Wooden Beam',
    shop_name_elite_beam: 'Elite Beam',
    shop_name_gunpowder: 'Gunpowder (x100)',
    shop_name_armor: 'Armor Plate (x100)',
    shop_name_elite_ship: 'Elite Ship I',
    shop_name_crystal_queen: 'Crystal Queen Design',
    stat_damage: 'Damage: {val}',
    stat_reload: 'Reload: {val}s',
    stat_damage_plus: 'Damage: +{val}',
    stat_elite_points: 'Elite Points: {val}x',
    stat_hp_plus: 'HP Bonus: +{val}',
    stat_repair_plus: 'Repair: +{val}',
    stat_damage_pct: 'Damage: +{val}%',
    stat_damage_reduction: 'Damage Reduction: {val}%',
    stat_hp: 'Hit Points: {val}',
    stat_cannon_slots: 'Cannon Slots: {val}',
    stat_mast_slots: 'Mast Slots: {val}',
    stat_skin: 'Skin: {val}',
    stat_note_cosmetic: 'Cosmetic only change.',
    stat_explosive_mult: '×1.6 Multiplier',
    rank_1: 'Ruler of the Seven Seas',
    rank_2: 'Pirate King',
    rank_3: 'Prince of Pirates',
    rank_4: 'Baron of the Seas',
    rank_5: 'Buccaneer',
    rank_6: 'Swashbuckler',
    rank_7: 'Corsair',
    rank_8: 'Coastal Raider',
    rank_9: 'Rookie Pirate',
    rank_10: 'Sailor',
    rank_11: 'Navigator',
    rank_12: 'Helmsman',
    rank_13: 'Boatswain',
    pvp_rank_1: 'Crew',
    pvp_rank_2: 'Apprentice Sailor',
    pvp_rank_3: 'Sailor',
    pvp_rank_4: 'Senior Sailor',
    pvp_rank_5: 'Apprentice Helmsman',
    pvp_rank_6: 'Helmsman',
    pvp_rank_7: 'Senior Helmsman',
    pvp_rank_8: 'Boatswain',
    pvp_rank_9: 'Senior Boatswain',
    pvp_rank_10: 'Second Captain',
    pvp_rank_11: 'First Captain',
    pvp_rank_12: 'Captain',
    pvp_rank_13: 'Senior Captain',
    pvp_rank_14: 'Fleet Commander',
    pvp_rank_15: 'Senior Fleet Commander',
    pvp_rank_16: 'Commodore',
    pvp_rank_17: 'Senior Commodore',
    pvp_rank_18: 'Admiral',
    pvp_rank_19: 'Senior Admiral',
    pvp_rank_20: 'Grand Admiral',
    pvp_rank_21: 'Fleet Admiral',
    pvp_rank_22: 'Lord of the Seas',
    pvp_rank_23: 'Pirate King',
    pvp_rank_24: 'Pirate Emperor',
    pvp_rank_25: 'Master of the Seas',
    pvp_rank_26: 'Legendary Captain',
    pvp_rank_27: 'Shadow Hunter',
    pvp_rank_28: 'Storm Rider',
    pvp_rank_29: 'Dragon Hunter',
    pvp_rank_30: 'Leviathan Hunter',
    pvp_rank_31: 'Guardian of the Depths',
    pvp_rank_32: "Poseidon's Chosen",
    pvp_rank_33: 'North Star',
    pvp_rank_34: 'Tsunami Bearer',
    pvp_rank_35: 'Judge of the Seas',
    pvp_rank_36: 'Kraken Conqueror',
    pvp_rank_37: 'Ghost Ship Captain',
    pvp_rank_38: 'Immortal Pirate',
    pvp_rank_39: 'Ancient Mariner',
    pvp_rank_40: 'Conqueror of the Seas',
    pvp_rank_51: 'Baron',
    pvp_rank_52: 'Visionary Captain',
    pvp_rank_53: 'Ascended Admiral',
    pvp_rank_54: 'Sovereign',
    pvp_rank_55: 'Lord of Oceans',
    pvp_rank_58: 'Cosmic Pirate',
    pvp_rank_59: 'Eternal Sailor',
    pvp_rank_60: 'SeaPirate Deity',
    item_gold_amount: '{val} Gold',
    item_pearl_amount: '{val} Pearl',
    item_hollow_amount: '{val} Hollow',
    item_explosive_amount: '{val} Explosive',
    item_gunpowder_amount: '{val}x Gunpowder',
    item_armor_amount: '{val}x Armor Plate',
    item_mixed_rewards: '{p} Pearl + {e} Explosive',
    item_gunpowder_armor: '{val}x Gunpowder & Armor Plate',
    home_title: 'Home',
    events_placeholder_name: 'Event',
    events_placeholder_desc: 'Description',
    starter_pack_title: 'STARTER PACK',
    pack_subtitle: 'One-time opportunity for new pirates!',
    btn_buy: 'Buy',
    rank_default: 'Landlubber',
    alt_current_rank: 'Current Rank',
    alt_next_rank: 'Next Rank',
    alt_ship: 'Ship',
    disconnect_title: 'CONNECTION LOST',
    disconnect_sub: 'Reconnecting...',
    level_label: '⭐ Level',
    alt_gold: 'Gold',
    menu_title: 'Menu',
    coordinate: 'Coordinate',
    equip_all_failed: 'Failed to equip all!',
    equip_failed: 'Failed to equip!',
    equip_load_failed: 'Failed to load equipment!',
    ships_load_failed: 'Failed to load ships!',
    time_hour: 'hour',
    unequip_all_failed: 'Failed to unequip all!',
    unequip_failed: 'Failed to unequip!'
};

var currentLang = localStorage.getItem('sp_lang') || 'en';
var _langCallbacks = [];
var _loadingLang = null;

function t(key, params) {
  if (params === void 0) params = {};
  var data = I18N_DATA[currentLang];
  if (!data) data = I18N_DATA['en'];
  var val = data ? data[key] : null;
  if (!val && currentLang !== 'en') {
    data = I18N_DATA['en'];
    val = data ? data[key] : null;
  }
  if (!val) return key;
  if (params && typeof val === 'string') {
    for (var k in params) {
      val = val.replace(new RegExp('\\{' + k + '\\}', 'g'), params[k]);
    }
  }
  return val;
}

function loadLanguage(lang, callback) {
  if (I18N_DATA[lang]) {
    if (callback) callback();
    return;
  }
  if (_loadingLang === lang && _langCallbacks.length > 0) {
    if (callback) _langCallbacks.push(callback);
    return;
  }
  _loadingLang = lang;
  if (callback) _langCallbacks.push(callback);

  var script = document.createElement('script');
  script.src = 'js/lang/' + lang + '.js';
  script.onload = function () {
    _loadingLang = null;
    var cbs = _langCallbacks.slice();
    _langCallbacks = [];
    for (var i = 0; i < cbs.length; i++) cbs[i]();
  };
  script.onerror = function () {
    if (lang !== 'en') {
      loadLanguage('en', callback);
    } else {
      _loadingLang = null;
      _langCallbacks = [];
      try { if (typeof applyI18n === 'function') applyI18n(); } catch (e) {}
      try { document.documentElement.classList.remove('i18n-loading'); } catch (e) {}
    }
  };
  document.head.appendChild(script);
}

function setLanguage(lang) {
  if (!lang) return false;
  currentLang = lang;
  localStorage.setItem('sp_lang', lang);

  loadLanguage(lang, function () {
    applyI18n();
    window.dispatchEvent(new Event('languageChanged'));
  });

  return true;
}

function applyI18n() {
  document.querySelectorAll('[data-i18n]').forEach(function (el) {
    var key = el.getAttribute('data-i18n');
    if (key) {
      var target = el.querySelector('[data-i18n-text]') || el;
      target.innerHTML = t(key);
    }
  });
  document.querySelectorAll('[data-i18n-placeholder]').forEach(function (el) {
    var key = el.getAttribute('data-i18n-placeholder');
    if (key) el.placeholder = t(key);
  });
  document.querySelectorAll('[data-i18n-title]').forEach(function (el) {
    var key = el.getAttribute('data-i18n-title');
    if (key) el.title = t(key);
  });
  document.querySelectorAll('[data-i18n-alt]').forEach(function (el) {
    var key = el.getAttribute('data-i18n-alt');
    if (key) el.alt = t(key);
  });
}

// After applying translations, reveal the page.
try {
  var _origApply = applyI18n;
  applyI18n = function () {
    _origApply();
    try { document.documentElement.classList.remove('i18n-loading'); } catch (e) {}
  };
} catch (e) { /* ignore if reassign fails */ }

window.t = t;
window.setLanguage = setLanguage;
window.applyI18n = applyI18n;
try {
  var _curDesc = Object.getOwnPropertyDescriptor(window, 'currentLang');
  if (!_curDesc || _curDesc.configurable) {
    Object.defineProperty(window, 'currentLang', { get: function () { return currentLang; }, configurable: true });
  } else {
    try {
      // If the property exists and is not configurable, avoid redefining it.
      // Attempt to keep the global value in sync instead.
      window.currentLang = currentLang;
    } catch (e) {
      // ignore
    }
  }
} catch (e) {
  try { window.currentLang = currentLang; } catch (er) { /* ignore */ }
}

if (currentLang !== 'en') {
  loadLanguage(currentLang, function () {
    applyI18n();
    window.dispatchEvent(new Event('languageChanged'));
  });
} else {
  document.addEventListener('DOMContentLoaded', function () {
    applyI18n();
    window.dispatchEvent(new Event('languageChanged'));
  });
}
